/**
 * Option lists for KYC text fields the UI renders as dropdowns.
 *
 * These are **presentation-only**. The server types every required text field
 * as `"text"` and receives a plain string either way (see `KycFieldInputType`
 * in `types/kyc.ts`), so constraining the input to a picker is safe and needs
 * no server change. Values are sent verbatim — keep them human-readable.
 */

/** Government-issued IDs accepted for identity verification. */
export const KYC_GOVERNMENT_ID_TYPES = [
  "NIN",
  "Driver's License",
  "International Passport",
  "Voter's Card",
] as const;

/** Nigerian states + FCT, alphabetical. */
export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Federal Capital Territory",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

/**
 * Countries of origin. Nigeria leads the list because it is the overwhelming
 * majority case for distributors; the remainder is alphabetical.
 */
export const KYC_COUNTRIES = [
  "Nigeria",
  "Algeria",
  "Angola",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Benin",
  "Botswana",
  "Brazil",
  "Burkina Faso",
  "Cameroon",
  "Canada",
  "Chad",
  "China",
  "Côte d'Ivoire",
  "Democratic Republic of the Congo",
  "Denmark",
  "Egypt",
  "Ethiopia",
  "France",
  "Gambia",
  "Germany",
  "Ghana",
  "Guinea",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kenya",
  "Lebanon",
  "Liberia",
  "Libya",
  "Malaysia",
  "Mali",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Netherlands",
  "New Zealand",
  "Niger",
  "Norway",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Sierra Leone",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Turkey",
  "Uganda",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
] as const;

export const toSelectOptions = (values: readonly string[]) =>
  values.map((value) => ({ label: value, value }));
