import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProviders } from "./providers";

const urbanist = localFont({
  src: [
    {
      path: "./fonts/Urbanist-Variable.ttf",
      style: "normal",
      weight: "100 900",
    },
  ],
  variable: "--font-urbanist",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Baiy App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo-small-primary.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased flex min-h-screen flex-col`}>
        <AppProviders>
          <main className="grow">{children}</main>
        </AppProviders>
      </body>
    </html>
  );
}
